#Database Config (MySQL)
hostname: 'localhost'
port: 3306
database: 'My_Stats'
username: 'root'
password: 'yourPassword'

#Discord BOT config
bot_token: 'yourBotToken'
channel_id: 1234567890 #yourChannelID

#Others
use_debug: false