#Database Config (MySQL)
hostname: 'localhost'
port: 3306
database: 'My_Stats'
username: 'root'
password: 'yourPassword'

#DiscordSRV config
notify_stats_update_to_discord: false
notify_message: 'Player statistics of <player> has been updated. Check it out on https://example.com'

#Others
use_debug: false