#Database Config (MySQL)
hostname: 'localhost'
port: 3306
database: 'My_Stats'
username: 'root'
password: 'yourPassword'

#Discord BOT config
bot_token: 'yourBotToken'
stat_channel_id: 1234567890 #your Stats Channel ID
general_channel_id: 1234567890 #your General Channel ID

#Others
use_debug: false